### ISSUE TITLE
Why not make it global?

### ISSUE THREAD

**Issue by stuartpb** [neveragaindottech/neveragaindottech.github.io#342]
Similar to the change proposed in #52, while we're proposing changes to the terms of the pledge:

```
@@ -69,7 +69,7 @@
 <ul>
   <li>We refuse to participate in the creation of
   databases of identifying information
-   for the United States government
+   for any government, at home or abroad,
   to target individuals based on race, religion, or national origin.

   <li>We will advocate within our organizations:
```

This seems especially prudent when you consider that the main cited impetus for this declaration was an American company building such a database for the *German* government.

**Comment by lode** [comment]
In the same way, is the wish to restrict this to "organizations and companies based in the United States"? The same issue plays all over the world.

I can imagine you want to restrict it if you want to hand this list over to a single government. But otherwise lets open it up for people from all over the world who are feeling the same.

**Comment by Arrow7000** [comment]
I agree. I work in tech in the UK but want to show my support for this too.

**Comment by daveloyall** [comment]
Unfortunately: #1579

**Comment by danielquinn** [comment]
@daveloyall I'm not sure #1579 applies here.  Patching the pledge to allow non-US citizens to sign doesn't change the statement of the document at all.  Signatories would still refuse to do the things outlined, it's just that the pledge would no longer require you to be American.

**Comment by lizthegrey** [comment]
non-US citizens are able to sign the pledge. The specific requirement is to be (1) based in the US, or (2) work for an employer headquartered in and/or with offices in the US, since those are the people most likely to be strongarmed or otherwise coopted into working on surveillance projects by the US government.

If you wish to fork the pledge and reset the signatories, or collaborate on a version 2 you'd be welcome to, but as per #1579 we can't modify the pledge text without potentially violating consent of the existing signatories.

**Comment by lode** [comment]
I understand modifying the text is not really an option.

I was wondering if there's a way around it to support people wanting to pledge anyway. I was thinking of adding a footnote at the US sentence, stating non-US-people are welcome and won't be blocked from adding their name. This would not really alter the pledge itself, but more show the organizers' consent.
