### ISSUE TITLE
Consider Also Listing Support for Sexual Orientation and Identity

### ISSUE THREAD

**Issue by theory** [neveragaindottech/neveragaindottech.github.io#52]
@@ -69,7 +69,7 @@
       <li>We refuse to participate in the creation of
       databases of identifying information
       for the United States government
    -  to target individuals based on race, religion, national origin, or sexual orientation or identity.
    +  to target individuals based on race, religion, or national origin.
 
       <li>We will advocate within our organizations:
         <ul>

If so, should probably also add it to the bullets under "We will advocate within our organizations".

**Comment by stuartpb** [comment]
:+1:, though it's worth pointing out that you should probably get everybody who signed the list already to reaffirm their commitment to the amended text or remove their name (similar to the procedure around changing licenses without a CLA).

**Comment by stuartpb** [comment]
@theory Nitpick: that patch (as written at time of this comment) is reversed (the `-` line should be the `+` and vice versa).

Also, I'd propose that, to allow room for future expansion (to address any future developments in discriminatory criteria that may be proposed), the terms should be thus:

```
@@ -69,7 +69,8 @@
   <li>We refuse to participate in the creation of
   databases of identifying information
   for the United States government
-  to target individuals based on race, religion, or national origin.
+ to target individuals based on aspects of personal identity, including but not limited to
+ race, religion, national origin, and sexual orientation or identity.

   <li>We will advocate within our organizations:
     <ul>
```

**Comment by theory** [comment]
@stuartpb D'oh!

**Comment by theory** [comment]
If there was the chance of getting a nationalized healthcare system, that would be a conversation worth having. Alas, it's not gonna happen anytime soon. Besides, you could make the same argument for ethnic identity (think tracking Tay-Sachs disease or Sickle Cell Anemia).

**Comment by ArchimedesPi** [comment]
It would be interesting to make this as wide as possible by talking about "any PII that enables systematic targeting of a group".

**Comment by stuartpb** [comment]
> "any PII that enables systematic targeting of a group".

"Targeting of a group" is too broad. That would preclude engineers from working on a system that implements tax brackets or means-adjusted benefits programs.

**Comment by khm** [comment]
I thought long and hard before attempting to sign this pledge.  In the end I did so because the goals are achievable.  I'm not sure if that would still be true if this change were made.  For instance:  just about every dating site would be hands-off after signing this pledge. 

 I think these other issues are important but it is not necessarily wise to broaden the scope of this pledge due to the risks of unintended consequences.  As it stands, the goal is clear and the specific class of travesty we intend to avoid is well-targeted.  

I encourage someone to start a second pledge for this topic.  Even if neveragain.tech hosts it, it would be wise to separate these concerns so domain experts in each area can work to refine the language and intent of a specific topic.

**Comment by lizthegrey** [comment]
We cannot update the pledge text (see above #1579 ); however, a forked version 2 of the pledge could be created in future with a reset list of signatories.
