### ISSUE TITLE
Why isn't american history not included in this?

### ISSUE THREAD

**Issue by Licenser** [neveragaindottech/neveragaindottech.github.io#889]
I find it disturbing that the pledge seems to completely ignore American history, not a single word is lost about the genocide of the native Americans neither is slavery mentioned which while not genocide was the systematic abuse of a race.

**Comment by khm** [comment]
Those particular travesties did not involve mass deportations or information technology, though.

**Comment by Licenser** [comment]
And that changes it in what way? I'm sure you're not saying that genocide or deportation is OK as long as IT isn't used, or that we should care less about it if IT isn't use. I think there were slave registers (could be mistaken here) and while not in a electronic form that doesn't make much of a difference I think.

**Comment by khm** [comment]
It changes it because this is a pledge not to use information technology to enable mass deportations.  The Armenian example is given as an example that mass deportation can have dire consequences.  The German example serves to highlight the potentialities of information technology in these atrocities and the Japanese-American internment is give as an example of a relatively recent and totally unacceptable action of the US government.  

I just don't understand what would be gained, as important as that history is, by including it in the text of the pledge, that's all.  It's important to stick tightly to the specific issue at hand so as not to give malicious critics a red herring with which to redirect the conversation away from the focus of this pledge.

This is more than a general statement of opposition to government abuse; it is a specific and actionable pledge not to support or enable particular government misbehavior.  While it is absolutely crucial for us all to have a clear understanding of the history of our nation, in order to be effective this pledge should not deviate from its immediate topic.

**Comment by Licenser** [comment]
It matters because it directly affects the "this can't happen here" mentality which can be argued to be part of the reason the US is where it is today. It matters because this is not a theoretical some-other-nations problem but one that's at the very foundation of the US. But of cause you can just narrow your scope to the point where it's easy and convenient to ignore the matter.

**Comment by khm** [comment]
Nobody is advocating ignoring anything.  You're arguing a widening of scope; I'm arguing scope should not be widened.  That's all.

The incoming administration has explicitly advocated both mass deportation and religion-based registration.  Those are the specific actions addressed by this pledge.  If the incoming administration advocated slavery or genocide, it would be appropriate for this pledge to address that.

**Comment by ryanprior** [comment]
First, changing the pledge after a thousand people have signed it would undermine the legitimacy of the pledge. It might seem reasonable to assume that people who oppose building a religious database or aiding mass deportation would also pledge to oppose slavery and native genocide, but to just put those words into signatories mouths wouldn't be right.

Second, multiple points of U.S. history are already referenced in the pledge: IBM's participation in the Holocaust and internment of Japanese-Americans. American history is included, especially the major events in recent history which combine the tech industry with mass human rights abuses and worse. We need not couch every statement about mass deportation being bad with "slavery and native genocide are also bad."

**Comment by lizthegrey** [comment]
See #1579  - the pledge can no longer be updated, sorry :/ - but you are welcome to fork and reset signatories if you like.
